# =========================
# Basic Site Settings
# =========================
locale         : "en-US"
site_theme     : "default"   # or "air" if your fork supports it
title          : "Nikhil Basavappa"
title_separator: "-"
name          : &name "Nikhil Basavappa"
description   : &description "PhD Candidate, Development & Environmental Economics"
url           : "https://nikhilbasavappa.github.io"   # no trailing slash
baseurl       : ""                                     # empty for username.github.io
repository    : "nikhilbasavappa/nikhilbasavappa.github.io"

# =========================
# Author (sidebar card)
# =========================
author:
  avatar   : "images/headshot.jpg"   # place your headshot at /images/profile.png
  name     : "Nikhil Basavappa"
  pronouns :
  bio      : "PhD Candidate in Economics at Columbia University."
  location : "New York, NY"
  employer : "Columbia University"
  uri      :
  email    : "nikhil.b [at] columbia.edu"

  # Leave all academic/social fields blank so no icons render:
  googlescholar :
  orcid         :
  researchgate  :
  linkedin      :
  twitter       :
  mastodon      :
  github        :
  bitbucket     :
  kaggle        :
  stackoverflow :

# Social schema (kept empty)
social:
  type  : Person
  name  : *name
  links : []

# =========================
# Site Options
# =========================
breadcrumbs      : false
words_per_minute : 160
future           : true
read_more        : "disabled"
talkmap_link     : false

comments:
  provider: false   # disable comments sitewide

atom_feed:
  hide: false
  path:

# =========================
# Analytics
# =========================
analytics:
  provider: false   # or "google-analytics-4" later
  google:
    tracking_id:

# =========================
# Build / Reading
# =========================
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .asset-cache
  - .bundle
  - .github
  - .sass-cache
  - CHANGELOG
  - Dockerfile
  - LICENSE
  - node_modules
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn

encoding     : "utf-8"
markdown_ext : "markdown,mkdown,mkdn,mkd,md"

# =========================
# Markdown / Highlight
# =========================
markdown        : kramdown
highlighter     : rouge
excerpt_separator: "\n\n"

kramdown:
  input         : GFM
  hard_wrap     : false
  auto_ids      : true
  footnote_nr   : 1
  entity_output : as_char
  toc_levels    : 1..6
  smart_quotes  : lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# =========================
# Collections (optional)
# Keep these if your fork expects them; you don't have to use them.
# =========================
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# =========================
# Default Front Matter
# =========================
defaults:
  - scope: { path: "", type: posts }
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

  - scope: { path: "", type: pages }
    values:
      layout: single
      author_profile: true

  - scope: { path: "", type: teaching }
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

  - scope: { path: "", type: publications }
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

  - scope: { path: "", type: portfolio }
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

  - scope: { path: "", type: talks }
    values:
      layout: talk
      author_profile: true
      share: false

# =========================
# Output / Timezone / Permalinks
# =========================
permalink: /:categories/:title/
timezone : America/New_York

# =========================
# GitHub Pages–compatible Plugins
# =========================
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag

# =========================
# Archives (optional)
# =========================
category_archive: { type: liquid, path: /categories/ }
tag_archive     : { type: liquid, path: /tags/ }

# =========================
# HTML Compression (optional)
# =========================
compress_html:
  clippings: all
  ignore:
    envs: development
